INTER-280 Add requirements section
fingerprintjs/fingerprintjs-pro-vue pull request #56
Opened 2023-09-26 11:40 UTC by TheUnderScorer

2023-09-26 17:05 UTC, ilfa approved these changes

2023-09-26 17:06 UTC, ilfa requested changes
Could you add `pnpm` snippets here too?

2023-09-27 13:34 UTC, ilfa approved these changes

2023-09-28 07:04 UTC, JuroUhlar requested changes

2023-09-28 07:04 UTC, JuroUhlar commented on packages/fingerprintjs-pro-vue-v2/README.md
Please address all the noticed issues also in the Vue 3 README consistently :)

2023-09-28 10:24 UTC, TheUnderScorer commented on packages/fingerprintjs-pro-vue-v2/README.md
Done!

2023-09-29 08:02 UTC, JuroUhlar approved these changes
Looking good, thank you!

2023-10-02 18:10 UTC, ilfa approved these changes

2023-10-05 12:20 UTC, merged

2023-10-05 12:23 UTC, ilfa commented
:tada: This PR is included in version 1.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@fingerprintjs/fingerprintjs-pro-vue-v2/v/1.2.1)
- [GitHub release](https://github.com/fingerprintjs/fingerprintjs-pro-vue/releases/tag/fingerprintjs-pro-vue2-v1.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: